# Generated by Django 4.2.6 on 2024-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Birthdate', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('High_school', models.CharField(max_length=30)),
                ('Essay', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='jalpa/')),
            ],
        ),
    ]
